spring.application.name=backend
server.port=9080
server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=jdbc:mysql://db:3306/portal_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=portal_user
spring.datasource.password=portal_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# File upload limits
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Email Service Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=portailmoodle@gmail.com
spring.mail.password=rppk xjkf vazh ozyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
